FROM debian:wheezy

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED true

RUN apt-get -qq update && \
    apt-get install -qy --no-install-recommends \
    python2.7 \
    python2.7-dev \
    gcc \
    python-pip

RUN pip install requests celery flower

EXPOSE 5555

ENTRYPOINT ["celery", "flower"]